### ISSUE TITLE
HTTP 504 Errors on API cause client to break

### ISSUE THREAD

**Issue by Xyaren** [JuxhinDB/gw2-api-interface#15]
Currently the api returns sporadic 504 errors which cause an Issue deep in the client.

```
2023-03-09 09:40:57,629.629 DEBUG  [MainThread] urllib3.connectionpool: https://api.guildwars2.com:443 "GET /v2/account HTTP/1.1" 504 132
2023-03-09 09:40:57,634.634 ERROR  [MainThread] bot.event_looper: BOT Event: Something went wrong during message received from teamspeak server. Likely bad user command/message.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/bot/event_looper.py", line 167, in _handle_message_event
    self.handle_private_message(message, rec_from_id, rec_from_name, rec_from_uid)
  File "/usr/local/lib/python3.11/site-packages/bot/event_looper.py", line 250, in handle_private_message
    auth = AuthRequest(uapi, self._config.required_servers, int(self._config.required_level))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bot/TS3Auth.py", line 44, in __init__
    self.pushAccountAuth()
  File "/usr/local/lib/python3.11/site-packages/bot/TS3Auth.py", line 62, in pushAccountAuth
    self.getAccountDetails()
  File "/usr/local/lib/python3.11/site-packages/bot/TS3Auth.py", line 72, in getAccountDetails
    self.account_details = gw2api.account_get(self.key)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bot/gwapi/facade.py", line 101, in account_get
    return _check_error(api.account.get())
                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gw2api/objects/api_version_2/__init__.py", line 12, in get
    page_size=kwargs.get('page_size')).json()
                                       ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JuxhinDB** [comment]
This is quite weird -- can you try running on the latest main branch? The likely issue here is that the 504 response is being returned by intermediary load balancer(s) rather than the internal APIs and not adhering to the requesting content-type.

This should be a relatively quick fix if you would like to proceed with a PR (would be happy to mentor).

**Comment by Mystikite** [comment]
Latest commit should address this issue.   
@JuxhinDB:  Do you have a timeline for an updated PyPi package availability?

**Comment by JuxhinDB** [comment]
Thank you @Mystikite -- 0.6.0 _should_ have been pushed. It's been a long while since I've used PyPi so let me know if there are any issues. Closing this issue off.
